## Imports

In [235]:
import pandas as pd

In [236]:
businesses = pd.read_csv('yelp_business.csv')
businesses.columns

Index(['business_id', 'name', 'neighborhood', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars', 'review_count',
       'is_open', 'categories'],
      dtype='object')

In [237]:
len(businesses)

174567

In [63]:
businesses.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...

In [69]:
restaurants = businesses[businesses['categories'].str.contains("Restaurants")]
restaurants.head(50)

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...
5,o9eMRCWt5PkpLDE0gOPtcQ,"""Messina""",NaN,"""Richterstr. 11""",Stuttgart,BW,70567,48.727200,9.147950,4.0,5,1,Italian;Restaurants
10,XOSRcvtaKc_Q5H1SAzN20A,"""East Coast Coffee""",NaN,"""737 West Pike St""",Houston,PA,15342,40.241548,-80.212815,4.5,3,0,Breakfast & Brunch;Gluten-Free;Coffee & Tea;Fo...
14,fNMVV_ZX7CJSDWQGdOM8Nw,"""Showmars Government Center""",Uptown,"""600 E 4th St""",Charlotte,NC,28202,35.221647,-80.839345,3.5,7,1,Restaurants;American (Traditional)
15,l09JfMeQ6ynYs5MCJtrcmQ,"""Alize Catering""",Yonge and Eglinton,"""2459 Yonge St""",Toronto,ON,M4P 2H6,43.711399,-79.399339,3.0,12,0,Italian;French;Restaurants
19,Gu-xs3NIQTj3Mj2xYoN2aw,"""Maxim Bakery & Restaurant""",NaN,"""9665 Bayview Avenue, Unit 1-4""",Richmond Hill,ON,L4C 9V4,43.867565,-79.412662,3.5,34,1,French;Food;Bakeries;Restaurants
25,1K4qrnfyzKzGgJPBEcJaNQ,"""Chula Taberna Mexicana""",Leslieville,"""1058 Gerrard Street E""",Toronto,ON,M4M 3A6,43.669256,-79.335902,3.5,39,1,Tiki Bars;Nightlife;Mexican;Restaurants;Bars
28,Dj0S-Oe4ytRJzMGUPgYUkw,"""Panera Bread""",NaN,"""38295 Chestnut Ridge Rd""",Elyria,OH,44035,41.343078,-82.067140,2.0,4,1,Soup;Salad;Sandwiches;Restaurants
29,gAy4LYpsScrj8POnCW6btQ,"""Toast Cafe""",NaN,"""2429 Hwy 160 W""",Fort Mill,SC,29708,35.047287,-80.990559,3.5,6,0,Food;American (Traditional);Coffee & Tea;Resta...
30,nbhBRhZtdaZmMMeb2i02pg,"""Sunnyside Grill""",NaN,"""2777 Steeles Avenue W""",Toronto,ON,M3J 3K5,43.781816,-79.490433,5.0,3,1,Restaurants;Breakfast & Brunch
32,1_3nOM7s9WqnJWTNu2-i8Q,"""Le Bistro Balmoral""",Ville-Marie,"""305 Rue Sainte-Catherine O""",Montreal,QC,H2X 2A1,45.506772,-73.566725,3.0,8,0,Arts & Entertainment;Festivals;Restaurants;Fre...
33,FXHfcFVEfI1vVngW2gVOpw,"""Bampot House of Tea & Board Games""",NaN,"""201 Harbord Street""",Toronto,ON,M5S 1H6,43.661582,-79.408878,4.0,55,1,Coffee & Tea;Restaurants;Food;Mediterranean;Te...
40,tRVx2c89coruPRwYhGTcTw,"""Yuzu""",NaN,"""13603 Madison Ave""",Lakewood,OH,44107,41.476846,-81.786971,3.5,78,1,Nightlife;Izakaya;Comfort Food;Cocktail Bars;A...
44,BnuzcebyB1AfxH0kjNWqSg,"""Carrabba's Italian Grill""",NaN,"""245 Lancaster Ave""",Frazer,PA,19355,40.041003,-75.542497,3.5,25,0,Restaurants;Italian;Seafood
45,rDMptJYWtnMhpQu_rRXHng,"""McDonald's""",NaN,"""719 E Thunderbird Rd""",Phoenix,AZ,85022,33.607070,-112.064382,1.0,10,1,Fast Food;Burgers;Restaurants
46,1WBkAuQg81kokZIPMpn9Zg,"""Charr An American Burger Bar""",NaN,"""777 E Thunderbird Rd, Ste 107""",Phoenix,AZ,85022,33.607310,-112.063404,3.0,232,1,Burgers;Restaurants
50,-ooEO2YqDQVYNHnSF2BPfw,"""Restaurant Lucca""",Rosemont-La Petite-Patrie,"""12 Rue Dante""",Montréal,QC,H2S 1J5,45.532896,-73.613604,4.5,11,1,Italian;Restaurants
52,Pd52CjgyEU3Rb8co6QfTPw,"""Flight Deck Bar & Grill""",Southeast,"""6730 S Las Vegas Blvd""",Las Vegas,NV,89119,36.066914,-115.170848,4.0,13,1,Nightlife;Bars;Barbeque;Sports Bars;American (...
53,4srfPk1s8nlm1YusyDUbjg,"""Subway""",Southeast,"""6889 S Eastern Ave, Ste 101""",Las Vegas,NV,89119,36.064652,-115.118954,2.5,6,1,Fast Food;Restaurants;Sandwiches
54,n7V4cD-KqqE3OXk0irJTyA,"""GameWorks""",Southeast,"""6587 Las Vegas Blvd S, Ste 171""",Las Vegas,NV,89119,36.068259,-115.178877,3.0,349,1,Arcades;Arts & Entertainment;Gastropubs;Restau...
55,c_XbaJqhm-5ycSBOkVUBmg,"""Don Taco""",Ville-Marie,"""1855 Rue Saint Catherine Ouest, H3H 1M2""",Montreal,QC,H3H 1M2,45.493216,-73.580379,3.5,33,1,Restaurants;Mexican
57,spDZkD6cp0JUUm6ghIWHzA,"""Kitchen M""",Unionville,"""8515 McCowan Road""",Markham,ON,L3P 5E5,43.867918,-79.283687,3.0,80,1,Restaurants;Chinese
64,EJFdWX908N8Yc2XG0Lky8A,"""River Moon Cafe""",Lawrenceville,"""104 43rd St""",Pittsburgh,PA,15201,40.472735,-79.963265,4.0,5,0,Cafes;Restaurants
68,F31RycVVooeIOp9jsXmg6g,"""The Bluebird Cafe""",Cannonmills,"""5 Canonmills""",Edinburgh,MLN,EH3 5HA,55.962444,-3.197662,4.5,16,1,Breakfast & Brunch;Diners;Restaurants;Cafes;Br...
72,iPa__LOhse-hobC2Xmp-Kw,"""McDonald's""",NaN,"""1635 E Camelback Rd""",Phoenix,AZ,85016,33.508765,-112.046240,3.0,34,1,Restaurants;Burgers;Fast Food
75,o1fTwfqN0sDFNpV1CkOPPg,"""Crazy Mocha Coffee""",Lawrenceville,"""4032 Butler St""",Pittsburgh,PA,15201,40.469295,-79.961273,3.5,16,1,Restaurants;Sandwiches;Coffee & Tea;Food
76,-nHkhiuerqmfBG3v2v9O-g,"""Bruegger's Bagels""",NaN,"""5217 Clairton Blvd""",Pittsburgh,PA,15236,40.344194,-79.970963,2.5,5,1,Breakfast & Brunch;Bagels;Restaurants;Bakeries...
80,kKx8iCJkomVQBdWHnmmOiA,"""Little Caesars Pizza""",NaN,"""10720 E Southern Ave""",Mesa,AZ,85209,33.394877,-111.600194,2.5,4,1,Restaurants;Pizza
81,B5EZlEDH6AVDk8tQGHAGqg,"""Villa Tap""",Sherman,"""2302 Packers Ave""",Madison,WI,53704,43.123389,-89.355390,4.0,34,1,American (Traditional);Nightlife;Dive Bars;Res...
86,VXH7zXcZzXlmAVN8GSjGRQ,"""Thai Express""",NaN,"""4700 Keele Street""",Toronto,ON,M3J 1P3,43.774878,-79.494619,3.0,5,1,Imported Food;Specialty Food;Thai;Ethnic Food;...
88,YhV93k9uiMdr3FlV4FHjwA,"""Caviness Studio""",NaN,"""""",Phoenix,AZ,85001,33.449967,-112.070223,5.0,4,1,Marketing;Men's Clothing;Restaurants;Graphic D...
90,aFBCmJUYrPeol_P75QX7Jw,"""Fraticelli's Authentic Italian Grill""",NaN,"""10 Vogell Road""",Richmond Hill,ON,L4B 3K4,43.864333,-79.382411,3.0,88,1,Restaurants;Italian
91,F0fEKpTk7gAmuSFI0KW1eQ,"""Cafe Mastrioni""",Spring Valley,"""4250 S Rainbow Blvd, Ste 1007""",Las Vegas,NV,89103,36.111057,-115.241688,1.5,3,0,Italian;Restaurants
96,dTWfATVrBfKj7Vdn0qWVWg,"""Flavor Cuisine""",Scarborough,"""8 Glen Watford Drive""",Toronto,ON,M1S 2C1,43.787061,-79.276166,3.0,6,1,Restaurants;Chinese;Food Court
97,HAX1zec191t7QkT2sBZ76A,"""La Isla Cuban Restaurant""",NaN,"""1816 Galerea Blvd, Ste D""",Charlotte,NC,28270,35.137223,-80.734594,3.0,4,0,Restaurants;Cuban
101,VdlPZg2NAu8t8GkdbPLecg,"""Tandoori Times Indian Bistro""",NaN,"""8140 N Hayden Rd, Ste H115""",Scottsdale,AZ,85258,33.555212,-111.900456,3.5,263,1,Restaurants;Gluten-Free;Indian;Seafood
103,c7X2SdKxVJMaOnFROO8WEg,"""Finga Lickin' Caribbean Eatery""",NaN,"""2838 The Plz""",Charlotte,NC,28205,35.236823,-80.801084,4.5,21,1,Pizza;Food;Internet Cafes;Restaurants;Caribbean
104,1nhf9BPXOBFBkbRkpsFaxA,"""Mirage Grill & Lounge""",Yonge and Eglinton,"""117 Eglinton Avenue E""",Toronto,ON,M4P 1H4,43.707465,-79.394285,2.0,6,0,Breakfast & Brunch;Food;Coffee & Tea;Canadian ...
107,QkG3KUXwqZBW18A9k1xqCA,"""Red Lobster""",NaN,"""2810 North 75th Ave""",Phoenix,AZ,85035,33.478735,-112.221379,2.5,37,1,American (Traditional);Restaurants;Seafood
113,sJ0MYSAIVK28cMzh-s-NPA,"""Amaya Express""",Downtown Core,"""Eaton Centre, 220 Yonge St""",Toronto,ON,M5B 2L7,43.654067,-79.380081,2.5,34,1,Indian;Restaurants;Fast Food
116,gIVjdDWRnS1yDVpPF3oUeg,"""Pizza Pizza""",Milliken,"""7665 Kennedy Road""",Markham,ON,L3R 0L7,43.841217,-79.303936,4.0,8,1,Italian;Chicken Wings;Fast Food;Restaurants;Pizza
117,veXxt8rGY_RJPpA5QkHT9Q,"""Barrio""",NaN,"""2466 Fairmount Blvd""",Cleveland Heights,OH,44106,41.500586,-81.592278,3.5,97,1,Food;Restaurants;Tacos;Food Trucks;Mexican
118,T5CdfrZWw-uW9Y5L_sddqQ,"""Police Station Pizza""",NaN,"""7235 Steubenville Pike""",Oakdale,PA,15071,40.442828,-80.186293,3.0,9,0,Pizza;Restaurants
120,5XejqzaFmtkZMstJS5Iy-w,"""D'Lish Cafe""",NaN,"""503 W Thomas Rd""",Phoenix,AZ,85013,33.480301,-112.080586,4.0,37,0,Vegan;American (New);Restaurants;Sandwiches;Sa...
122,Wpt0sFHcPtV5MO9He7yMKQ,"""McDonald's""",Eastside,"""3020 E Desert Inn Rd""",Las Vegas,NV,89121,36.130013,-115.109310,2.0,20,1,Restaurants;Fast Food;Burgers
126,WUiDaFQRZ8wKYGLvmjFjAw,"""China Buffet""",University City,"""8630 University Executive Park Dr""",Charlotte,NC,28262,35.306173,-80.752672,3.5,76,1,Buffets;Restaurants;Sushi Bars;Chinese
127,nAFI7JZEhmvUKMKSA_5Chg,"""Nesenbach""",Rathaus,"""Dorotheenstr. 6""",Stuttgart,BW,70173,48.775453,9.180737,2.5,7,1,Cafes;Nightlife;Wine Bars;Bars;Restaurants
128,5q6Xh-UcJa78bp6dzyaE7w,"""Duck Donuts""",Dilworth,"""1710 Kenilworth Ave, Ste 220""",Charlotte,NC,28203,35.202624,-80.844419,4.5,373,1,Breakfast & Brunch;Food;Coffee & Tea;Donuts;Re...
130,MTH-AcNyWfsBa9sXp04HcQ,"""Firehouse Subs""",NaN,"""3420 E Baseline Rd, Ste 101""",Mesa,AZ,85204,33.379621,-111.757160,3.5,82,1,Food;Delis;Fast Food;Sandwiches;Restaurants
132,nigYwB_m1TQ1WosjSWi-Hw,"""Simply Burgers""",NaN,"""1455 W Elliot Rd""",Gilbert,AZ,85233,33.349658,-111.821238,3.0,5,0,Burgers;Restaurants

In [291]:
business_attr = pd.read_csv('yelp_business_attributes.csv')

In [293]:
len(business_attr)

152041

In [294]:
business_attr['business_id'].nunique()

152041

In [295]:
restaurant_attr = restaurants.merge(business_attr, left_on='business_id', right_on='business_id', how = 'inner')
restaurant_attr.columns

Index(['business_id', 'name', 'neighborhood', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars', 'review_count',
       'is_open', 'categories', 'AcceptsInsurance', 'ByAppointmentOnly',
       'BusinessAcceptsCreditCards', 'BusinessParking_garage',
       'BusinessParking_street', 'BusinessParking_validated',
       'BusinessParking_lot', 'BusinessParking_valet',
       'HairSpecializesIn_coloring', 'HairSpecializesIn_africanamerican',
       'HairSpecializesIn_curly', 'HairSpecializesIn_perms',
       'HairSpecializesIn_kids', 'HairSpecializesIn_extensions',
       'HairSpecializesIn_asian', 'HairSpecializesIn_straightperms',
       'RestaurantsPriceRange2', 'GoodForKids', 'WheelchairAccessible',
       'BikeParking', 'Alcohol', 'HasTV', 'NoiseLevel', 'RestaurantsAttire',
       'Music_dj', 'Music_background_music', 'Music_no_music', 'Music_karaoke',
       'Music_live', 'Music_video', 'Music_jukebox', 'Ambience_romantic',
       'Ambience_intimate', 'Ambience_classy', 'Ambience_hipster',
       'Ambience_divey', 'Ambience_touristy', 'Ambience_trendy',
       'Ambience_upscale', 'Ambience_casual', 'RestaurantsGoodForGroups',
       'Caters', 'WiFi', 'RestaurantsReservations', 'RestaurantsTakeOut',
       'HappyHour', 'GoodForDancing', 'RestaurantsTableService',
       'OutdoorSeating', 'RestaurantsDelivery', 'BestNights_monday',
       'BestNights_tuesday', 'BestNights_friday', 'BestNights_wednesday',
       'BestNights_thursday', 'BestNights_sunday', 'BestNights_saturday',
       'GoodForMeal_dessert', 'GoodForMeal_latenight', 'GoodForMeal_lunch',
       'GoodForMeal_dinner', 'GoodForMeal_breakfast', 'GoodForMeal_brunch',
       'CoatCheck', 'Smoking', 'DriveThru', 'DogsAllowed',
       'BusinessAcceptsBitcoin', 'Open24Hours', 'BYOBCorkage', 'BYOB',
       'Corkage', 'DietaryRestrictions_dairy-free',
       'DietaryRestrictions_gluten-free', 'DietaryRestrictions_vegan',
       'DietaryRestrictions_kosher', 'DietaryRestrictions_halal',
       'DietaryRestrictions_soy-free', 'DietaryRestrictions_vegetarian',
       'AgesAllowed', 'RestaurantsCounterService'],
      dtype='object')

In [57]:
sum(restaurants['review_count'])

3221032

In [303]:
business_checkin = pd.read_csv('yelp_checkin.csv')
# restaurant_checkin = pd.merge(restaurant_attr['business_id'], business_checkin, 
#          left_on = 'business_id', right_on = 'business_id', how = 'inner')
business_checkin.sort_values('business_id').head()

                    business_id weekday   hour  checkins
537718   --6MefnULPED_I942VcFNA     Fri  21:00         1
1109174  --6MefnULPED_I942VcFNA     Mon   1:00         3
3243238  --6MefnULPED_I942VcFNA     Mon  23:00         1
3075089  --6MefnULPED_I942VcFNA     Wed  19:00         2
2362177  --6MefnULPED_I942VcFNA     Sat  22:00        11

**Total # of restaurants**

In [302]:
len(restaurants), len(restaurant_attr), restaurant_checkin['business_id'].nunique()

(54618, 53373, 51282)

**Restaurants in different states**

In [68]:
restaurants.groupby('state')['business_id'].count().reset_index().sort_values('business_id', ascending = False)
# sort_values('')

   state  business_id
31    ON        13501
6     AZ        10598
27    NV         7135
34    QC         4981
30    OH         4814
25    NC         3850
32    PA         3647
8     BW         1783
41    WI         1565
14   EDH         1460
21    IL          632
36    SC          213
24   MLN           96
12   CHE           66
19   HLD           63
29   NYK           59
17   FIF           31
15   ELN           21
42   WLN           20
10     C           19
28    NY           10
0     01           10
26    NI            8
37    ST            6
39    VS            3
22    IN            3
16   ESX            3
9     BY            3
13    CO            2
23   KHL            1
5     AK            1
43   XGL            1
2     30            1
3      6            1
40   WHT            1
4    ABE            1
38    VA            1
35   RCC            1
7      B            1
1      3            1
33   PKN            1
11    CA            1
18   GLG            1
20    HU            1
44   ZET            1

**Read all reviews**

In [238]:
reviews = pd.read_csv('yelp_review.csv')
len(reviews)
# reviews.head()

5261668

**Filter reviews by restaurants**

In [73]:
restaurant_reviews = reviews[reviews.business_id.isin(restaurants['business_id'])]

In [74]:
len(restaurant_reviews)

3221418

**Random sample 100k reviews**

In [112]:
restaurant_reviews_sample = restaurant_reviews.sample(n=100000, random_state=1)

In [114]:
restaurant_reviews_sample.to_csv('./yelp_restaurant_reviews_sample.csv', header = True, index = False)

In [115]:
restaurant_reviews_sample = pd.read_csv('yelp_restaurant_reviews_sample.csv')
restaurant_reviews_sample.head()

,review_id,user_id,business_id,stars,date,text,useful,funny,cool
0,ApmUOTRfk3pB6USCiSHl0Q,LMxsgATZnl_Vw0Kze7HdQQ,S_bG5WWbtNXhhY9Y0GTcSg,4,2016-09-21,Had the cheese quesadilla and a chai tea. It w...,0,0,0
1,TPBUEeKPKH1SfCDZQlFKkQ,UOKFUQlGWmMEjwiGFwACdQ,JQ4E1Im1dHMpDa1s4vJMoQ,4,2010-08-15,After looking at the other reviews about this ...,2,0,1
2,wdYB-bpUYt_lVodoKi56Ig,-od707p4FHGul0gte29AoQ,Yv4P4qUwd7F-qQ4Y4eD1JQ,3,2016-12-21,So I may not be the best person the review thi...,0,0,0
3,RMeMYKXgKjCa2gJ03APC7g,SdxHtbvFQJAgPUkQfE4CIQ,Q2ZNaN3p8s_-XXjBWyY2qA,5,2014-06-05,I'm here for a VMWare presentation lunch. The...,0,1,0
4,nXCAYS5UQnuw-CbhGnf5pQ,30SOROHP54Tn6ELl_YgeXg,UFyzcr1y2r3y-e_tNpA9VA,2,2013-03-27,Was driving by Madison and thought we'd get so...,0,0,0

**Extract year**

In [116]:
restaurant_reviews_sample['review_year'] = restaurant_reviews_sample['date'].apply(lambda x:int(x[:4]))

**Look at distribution of reviews by year**

In [117]:
restaurant_reviews_sample.groupby(['review_year'])['review_id'].size().reset_index()

    review_year  review_id
0          2005         15
1          2006        119
2          2007        425
3          2008       1080
4          2009       2040
5          2010       3657
6          2011       5797
7          2012       6857
8          2013       9115
9          2014      13006
10         2015      17510
11         2016      19696
12         2017      20683

**Look at distribution of reviews by star**

In [118]:
restaurant_reviews_sample.groupby(['stars'])['review_id'].size().reset_index()

   stars  review_id
0      1      11395
1      2       9447
2      3      14090
3      4      27817
4      5      37251

**Create 1-0 sentiment flag**

In [119]:
restaurant_reviews_sample['sentiment'] = restaurant_reviews_sample['stars'].apply(lambda x: 1 if x >= 4 else 0)

**Drop reviews older than 2010**

In [159]:
relevant_reviews = restaurant_reviews_sample[(restaurant_reviews_sample['review_year'] > 2010)]
#                                              & (restaurant_reviews_sample['stars'] != 3)]

## Text Preprocessing

**Removing stop words**

In [234]:
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')

english_stop_words = stopwords.words('english')
def remove_stop_words(corpus):
    removed_stop_words = []
    for review in corpus:
        removed_stop_words.append(
            ' '.join([word for word in review.split() 
                      if word not in english_stop_words])
        )
    return removed_stop_words

relevant_reviews['cleaned_text'] = relevant_reviews['text'].apply(lambda x: remove_stop_words(x))

/Library/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

**Stemming/Lemmatization**

In [150]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

def get_lemmatized_text(corpus):
    lemmatizer = WordNetLemmatizer()
    return [' '.join([lemmatizer.lemmatize(word) for word in review.split()]) for review in corpus]

relevant_reviews['cleaned_text'] = relevant_reviews['cleaned_text'].apply(lambda x: get_lemmatized_text(x))

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/arunavsaikia/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
/Library/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

## Create Train/Validation/Test Split

In [160]:
from sklearn.model_selection import train_test_split

In [284]:

X_train_set, X_nottrain, y_train, y_nottrain = train_test_split(relevant_reviews['text'], 
                                                    relevant_reviews['sentiment'], 
                                                    test_size=0.30, 
                                                    random_state=42)

X_test_set, X_val_set, y_test, y_val = train_test_split(X_nottrain, 
                                                    y_nottrain, 
                                                    test_size=0.5, 
                                                    random_state=42)

In [162]:
y_train.value_counts()

1    40338
0    21746
Name: sentiment, dtype: int64

In [163]:
y_val.value_counts()

1    9959
0    5331
Name: sentiment, dtype: int64

In [164]:
y_test.value_counts()

1    10151
0     5139
Name: sentiment, dtype: int64

## Feature Engineering

**1-gram Binary**

In [254]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=True)
cv.fit(X_train_set)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

**1-gram Count**

In [266]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=False)
cv.fit(X_train)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

**2-gram Binary**

In [260]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=True, ngram_range=(1,2))
cv.fit(X_train)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

**2-gram Count**

In [273]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=False, ngram_range=(1,2))
cv.fit(X_train)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

**1-gram Tf-Idf**

In [279]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer()
cv.fit(X_train)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

**2-gram Tf-Idf**

In [285]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(ngram_range=(1,2))
cv.fit(X_train)
X_train = cv.transform(X_train_set)
X_test = cv.transform(X_test_set)
X_val = cv.transform(X_val_set)

In [252]:
X_test.shape

(15290, 1166319)

## Multiple Iterations

**Baseline Logistic Regression**

In [286]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

for c in [0.01, 0.05, 0.25, 0.5, 1]:
    
    lr = LogisticRegression(solver = 'lbfgs', 
                            penalty = 'l2', 
                            C=c,
                           max_iter= 300)
    lr.fit(X_train, y_train)
    print ("For C = %s, Accuracy: %s, F1-score: %s" 
           % (c, accuracy_score(y_val, lr.predict(X_val)), f1_score(y_val, lr.predict(X_val))))

For C = 0.01, Accuracy: 0.6777632439502943, F1-score: 0.8013867053654211
For C = 0.05, Accuracy: 0.8225637671680837, F1-score: 0.8770785193239997
For C = 0.25, Accuracy: 0.8821451929365598, F1-score: 0.9129552700222201
For C = 0.5, Accuracy: 0.8913015042511445, F1-score: 0.9188793440062475
For C = 1, Accuracy: 0.8983649444081099, F1-score: 0.9236288578730096

In [287]:
final_model = LogisticRegression(solver = 'lbfgs', 
                            penalty = 'l2', 
                            C=1,
                           max_iter= 300)
final_model.fit(X_train, y_train)
print ("Final Accuracy: %s, F1-score: %s" 
           % (accuracy_score(y_test, final_model.predict(X_test)), f1_score(y_test, final_model.predict(X_test))))

Final Accuracy: 0.8992805755395683, F1-score: 0.9255751014884979

In [246]:
feature_to_coef = {
    word: coef for word, coef in zip(
        cv.get_feature_names(), final_model.coef_[0]
    )
}
print("Best Positive")
for best_positive in sorted(
    feature_to_coef.items(), 
    key=lambda x: x[1], 
    reverse=True)[:15]:
    print (best_positive)

print("Best Negative")

for best_negative in sorted(
    feature_to_coef.items(), 
    key=lambda x: x[1])[:15]:
    print (best_negative)

Best Positive
('amazing', 1.2724722837440068)
('delicious', 1.1737709794276843)
('excellent', 1.1305861486631892)
('perfect', 0.978954089385003)
('wonderful', 0.9611709684293177)
('awesome', 0.9413331159338744)
('fantastic', 0.9162454708127878)
('great', 0.8480660120741754)
('perfection', 0.8475683063288447)
('gem', 0.8158036922826443)
('outstanding', 0.8004041710135689)
('incredible', 0.7707504782283447)
('glad', 0.7450359382588764)
('disappoint', 0.7311391578098594)
('notch', 0.7120859527587003)
Best Negative
('worst', -1.5827269516329685)
('mediocre', -1.3689471266299473)
('horrible', -1.3361157643800066)
('terrible', -1.2331055550072083)
('rude', -1.2229319988732033)
('bland', -1.185029372274528)
('ok', -1.1605387989842268)
('overpriced', -1.0890524856738717)
('disappointing', -1.001755375281107)
('average', -0.9410541741997671)
('poor', -0.9359040881242008)
('unfortunately', -0.890757970045028)
('okay', -0.8764995803719366)
('tasteless', -0.8649364302789874)
('meh', -0.8481321085128276)

**Baseline SVM**

In [288]:
from sklearn.svm import LinearSVC

for c in [0.01, 0.05, 0.25, 0.5, 1]:
    
    svm = LinearSVC(C=c, max_iter=400)
    svm.fit(X_train, y_train)
    print ("For C = %s, Accuracy: %s, F1-score: %s" 
           % (c, accuracy_score(y_val, svm.predict(X_val)), f1_score(y_val, svm.predict(X_val))))

For C = 0.01, Accuracy: 0.8585349901896665, F1-score: 0.8986172955237872
For C = 0.05, Accuracy: 0.8939175931981688, F1-score: 0.9208934841982053
For C = 0.25, Accuracy: 0.907782864617397, F1-score: 0.9304047384007897
For C = 0.5, Accuracy: 0.9076520601700457, F1-score: 0.9301405105877696
For C = 1, Accuracy: 0.9079790712884238, F1-score: 0.9302533088782036

In [289]:
final_model = LinearSVC(C=0.25, max_iter=400)

final_model.fit(X_train, y_train)
print ("Final Accuracy: %s, F1-score: %s" 
           % (accuracy_score(y_test, final_model.predict(X_test)), f1_score(y_test, final_model.predict(X_test))))

Final Accuracy: 0.9045127534336167, F1-score: 0.9292018232955096

**Baseline Naive Bias**

**Baseline NBSVM** (cite)

## TIPS

In [170]:
tips = pd.read_csv('./yelp_tip.csv')
tips.head()

,text,date,likes,business_id,user_id
0,Great breakfast large portions and friendly wa...,2015-08-12,0,jH19V2I9fIslnNhDzPmdkA,ZcLKXikTHYOnYt5VYRO5sg
1,Nice place. Great staff. A fixture in the tow...,2014-06-20,0,dAa0hB2yrnHzVmsCkN4YvQ,oaYhjqBbh18ZhU0bpyzSuw
2,Happy hour 5-7 Monday - Friday,2016-10-12,0,dAa0hB2yrnHzVmsCkN4YvQ,ulQ8Nyj7jCUR8M83SUMoRQ
3,"Parking is a premium, keep circling, you will ...",2017-01-28,0,ESzO3Av0b1_TzKOiqzbQYQ,ulQ8Nyj7jCUR8M83SUMoRQ
4,Homemade pasta is the best in the area,2017-02-25,0,k7WRPbDd7rztjHcGGkEjlw,ulQ8Nyj7jCUR8M83SUMoRQ

In [171]:
restaurant_tips = tips[tips.business_id.isin(restaurants['business_id'])]

In [202]:
restaurant_tips.groupby('business_id')['text'].size().reset_index().sort_values('text', ascending = False)

                  business_id  text
10462  DkYS3arLOhA8si5uUEmHOw  1474
15057  K7lWdNUhCbcnEvI0NhGewg  1346
32463  hihud--QRriCYZw1zZvW4g  1287
20048  RESDUcs7fIiihp38-d6_6g  1149
44492  yfxDa8RFOvJPQh0rNtakHA  1062
3744   4JNXUYY8wbaaDmk3BPzlWw  1038
32817  iCQpiavjjPzJ5_3gPD5Ebg  1033
6230   7sPNbCx7vGAaH7SbNPZ6oA   981
22336  UPIYuRaZvknINOd1w8kqRQ   959
30417  eoHdUeQDNgQ6WYEnP2aiRw   940
14922  JyxHvtj-syke7m9rbza7mA   888
15916  LNGBEEelQx4zbfWnlc66cw   854
30623  f4x1YBxkLrZg652xt2KR5g   800
11166  El4FC8jcawUVgw_0EIcbaQ   759
28817  cYwJA2A6I12KNkm2rtXd5g   753
15564  KskYqH1Bi7Z_61pH6Om8pg   750
14927  JzOp695tclcNCNMuBl7oxA   718
31333  g8OnV26ywJlZpezdBnOWUQ   678
27696  awI4hHMfa7H0Xf0-ChU5hg   666
20518  RwMLuOkImBIqqYj4SSKSPg   654
10755  EAwh1OmG6t6p3nRaZOW_AA   642
18525  P7pxQFqr7yBKMMI2J51udw   625
24570  XXW_OFaYQkkGOGniujZFHg   608
2804   2weQS-RnoOBhb1KsHKyoSQ   599
18213  OgJ0KxwJcJ9R5bUK0ixCbg   588
45163  zdE82PiD6wquvjYLyhOJNA   579
17678  NvKNe9DnQavC9GstglcBJQ   575
7863   A5Rkh7UymKm0_Rxm9K2PJw   573
41668  ugLqbAvBdRDc-gS4hpslXw   572
4822   5shgJB7a-2_gdnzc0gsOtg   569
...                       ...   ...
30049  eGhPPX148Cs3YSXzORz9Jw     1
30050  eGt0GhiFS0FPJNRGJkp0fw     1
30051  eH2dLnYL-neGHWntfNrtZA     1
30053  eH96MBK-EAcC0Q-lYqIb8Q     1
29952  e6o3qQAF6YU_5U2L4qCXAA     1
5545   6tR-uUoy8CScXuSRMw2igQ     1
5578   6wZdg1ursk12C3CTnF0gcg     1
29947  e6ObnvluEdZfpN3tlm0Daw     1
29877  e0Vvrs1M-oMhNBg_8uc6ZQ     1
5576   6wZBf3JN-v1_o8eyz2LCvA     1
29889  e1UF53wfi3HKNmPHzc3OLg     1
5572   6w2aw3EM4K_cIFpQOWCMCw     1
29893  e1jI2-vU1fd4UKpyogtxuA     1
29894  e1lvyKk6xlh3xEJ3L2dxlg     1
29900  e2IqS9_G0Hpulw5ItU-Y9Q     1
5563   6ugDF5tRRX5l3Q5vrdkprg     1
29911  e3QhVshZfZYCF1fEhwu5Cw     1
29912  e3dbqeMI4k1Jl2VBCq9rNw     1
29919  e4KIOV59c_b4o4N5oorIxw     1
5557   6u4tFgTFUgj9veFeUgyytA     1
29926  e53Fsnz4uf6seDeU7Q328g     1
5553   6tm4ttFRiSZEyGFXikqWtw     1
5552   6tlbZydPbL0Q3_eolg2OJA     1
5551   6tl_UiTs8uqZO3iSfdMZmA     1
29932  e5WAfCqfd_66zgrHmn8CiQ     1
29935  e5dj4h4vTvZYQvKPnBvDjw     1
29936  e5gaYL_VMcyRbifne9D17w     1
29937  e5lUODtid2iv9Ei2gkqRBw     1
29942  e68xTl12ry5-RMEvWulUoA     1
28700  cPWbolWE6ip5SupmfH-nBQ     1

[45424 rows x 2 columns]

In [230]:
xx = restaurant_tips[restaurant_tips['business_id'] == 'K7lWdNUhCbcnEvI0NhGewg']
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')

english_stop_words = stopwords.words('english')
def remove_stop_words(corpus):
    removed_stop_words = []
    for review in corpus:
        removed_stop_words.append(
            ' '.join([word for word in review.split() 
                      if word not in english_stop_words])
        )
    return removed_stop_words

xx_cleaned = xx['text'].apply(lambda x: remove_stop_words(x))

In [233]:
xx

,text,date,likes,business_id,user_id
1710,Buffet entrance,2013-06-08,0,K7lWdNUhCbcnEvI0NhGewg,9_FuvIsmM6RwjXo8eqXsCw
9315,We went for the brunch with unlimited bloodyin...,2012-09-02,0,K7lWdNUhCbcnEvI0NhGewg,_4Wwqc9CcI8jBPzfxyg6kw
20539,$37 Sunday \/ Saturday mimosa brunch. Really l...,2012-04-28,0,K7lWdNUhCbcnEvI0NhGewg,6K7j8OiLChFflIrh95Pn4A
20540,No sticky buns or macarons??!! A weekend only ...,2014-07-14,0,K7lWdNUhCbcnEvI0NhGewg,6K7j8OiLChFflIrh95Pn4A
20624,"If you are going for Sunday brunch, get there ...",2013-08-11,0,K7lWdNUhCbcnEvI0NhGewg,N-pi-twvDI08ubRth9q0kw
21049,Slab of bacon - best meat on the buffet,2012-03-02,0,K7lWdNUhCbcnEvI0NhGewg,j9tEVrwdzlfHHJ-dz3dWrQ
22351,"Brunch buffet with unlimited mimosas? Yes, let...",2011-11-05,0,K7lWdNUhCbcnEvI0NhGewg,UAgziBeRHHqkYdxqcKjldA
22352,Best buffet in Vegas! Unlimited mimosas!,2012-04-01,0,K7lWdNUhCbcnEvI0NhGewg,UAgziBeRHHqkYdxqcKjldA
22353,The GF and i love it! Best buffet in Vegas!,2012-06-29,0,K7lWdNUhCbcnEvI0NhGewg,UAgziBeRHHqkYdxqcKjldA
25112,Herman is a greater server. With just a glance...,2014-03-02,0,K7lWdNUhCbcnEvI0NhGewg,OLGQ7alK4VKl3YdQk6UF5g
28306,Here for $40 Mother's Day special buffet. Not ...,2012-05-13,0,K7lWdNUhCbcnEvI0NhGewg,IWFWaJZC8tBPMVPcoPNSdA
51101,A comp brings me back for lunch - this is one ...,2010-12-21,0,K7lWdNUhCbcnEvI0NhGewg,MlnuJ7T14CE0JDK2ZIOx5g
52499,One of the most unique buffets in LV!,2013-01-08,0,K7lWdNUhCbcnEvI0NhGewg,0JgjdJUgsMxh8U9-RWSomw
63048,Eating marrow for the first time. Yum.,2011-05-08,0,K7lWdNUhCbcnEvI0NhGewg,hhYo5WYOjNlHhVa3IXXwUQ
63511,Inside the Cosmopolitan! Fancy!,2012-05-05,0,K7lWdNUhCbcnEvI0NhGewg,pLlRrcoDrzX7QSlTTcG0ow
65418,Buffet brunch! $26+tax,2011-03-13,0,K7lWdNUhCbcnEvI0NhGewg,fa_SC0SFxcktQvgT4vrtfQ
65584,"Wicked buffet with all the fattening, healthy ...",2012-09-05,0,K7lWdNUhCbcnEvI0NhGewg,XMm7FsdMuJgJ7gpmM1Npfw
68787,Delicious prime rib!! I'd go back just for tha...,2015-12-23,0,K7lWdNUhCbcnEvI0NhGewg,ga_05brEylDLIabc3lZOgA
69110,Your ODM restaurant report... (One Dope Mexica...,2012-02-21,0,K7lWdNUhCbcnEvI0NhGewg,SSRrNLsHuQbDhmfCGdyXTw
82078,Best buffet on the strip for foodies. Best pre...,2012-08-11,0,K7lWdNUhCbcnEvI0NhGewg,EbbOIQ5oAamS9D_B_7cC7w
82079,Gelato bar. 'Nuff said.,2012-08-11,0,K7lWdNUhCbcnEvI0NhGewg,EbbOIQ5oAamS9D_B_7cC7w
82080,Mac 'n Cheese bar. Best idea ever.,2012-08-11,0,K7lWdNUhCbcnEvI0NhGewg,EbbOIQ5oAamS9D_B_7cC7w
82081,"For $8 more you can get unlimited champagne, m...",2012-08-11,0,K7lWdNUhCbcnEvI0NhGewg,EbbOIQ5oAamS9D_B_7cC7w
83097,Marriott Platinum members get priority line & ...,2013-03-09,0,K7lWdNUhCbcnEvI0NhGewg,VEwewo3j4Qqjwa0T2VAObw
84864,"Well, this is just going to be out of control....",2012-07-15,0,K7lWdNUhCbcnEvI0NhGewg,LlIZmwJLnw7PMDktDiy6sw
96184,Tuesday 5pm - best time to go!,2013-03-12,0,K7lWdNUhCbcnEvI0NhGewg,7Pxx2FehELyKthPj0OY1sg
97072,Try everything,2013-04-12,0,K7lWdNUhCbcnEvI0NhGewg,BQLc7jSHfPXDvleNFJ6lyg
97853,Worth every penny...,2012-09-04,0,K7lWdNUhCbcnEvI0NhGewg,2VABkVdFhHGMo7wAqfofGA
101380,2 ~ 3 hours long lines.avoid if hungry and alr...,2013-12-27,0,K7lWdNUhCbcnEvI0NhGewg,jyvBsDjoj-Uz5z4ou4pmsw
114646,Carb loading part 2!,2011-12-04,0,K7lWdNUhCbcnEvI0NhGewg,lq9Of1AecrIE6IGcrJ3gvQ
...,...,...,...,...,...
975158,Food not hot. Wayne 5:30 pm is too early to g...,2017-02-07,0,K7lWdNUhCbcnEvI0NhGewg,WVJFyp0tG9HPrmo6-36BJg
975159,Definitely worth it! So many options that are ...,2017-02-16,0,K7lWdNUhCbcnEvI0NhGewg,lJm34omsrlz4bu3xJXtoHA
975160,Not worth the 50 minute wait or $36 brunch! Ba...,2017-02-25,0,K7lWdNUhCbcnEvI0NhGewg,HXaMtgedYDb7mSjduhfTUg
975161,I've lived in las Vegas for 30+ years and this...,2017-02-28,0,K7lWdNUhCbcnEvI0NhGewg,rGk5WtolboQe7PNeJEttGA
975163,$5 cocktails during happy hour (5-7pm everyday),2017-03-15,0,K7lWdNUhCbcnEvI0NhGewg,kon9fkee771ovY122yzq7w
975165,"Great food, unlimited mimosa's and bloody Mary's",2017-04-05,0,K7lWdNUhCbcnEvI0NhGewg,jFDA2zKBWh6TvijEq8StCA
975166,Good selection of many different foods. Would ...,2017-04-06,0,K7lWdNUhCbcnEvI0NhGewg,BIwmYp-a0_uT7fhaqYNT_g
975167,There is a lot of choices. It was good and tas...,2017-04-20,0,K7lWdNUhCbcnEvI0NhGewg,yJWdGGGNXbALwa4qua2xow
975169,"for once being in a big group has its perks, a...",2017-05-21,0,K7lWdNUhCbcnEvI0NhGewg,JCxqmnSKTnHprmsYKoe1ow
975174,Super fresh and nice quality food. Definitely ...,2017-05-25,0,K7lWdNUhCbcnEvI0NhGewg,KJNtY0bcv_8WAPp2xJujfA
975175,"Eh, the food was ok. There's a good selection ...",2017-06-05,0,K7lWdNUhCbcnEvI0NhGewg,4zQyI5P-9wMpkTxhnPZkSA
975176,This is definitely a buffet you need to go to ...,2017-06-11,0,K7lWdNUhCbcnEvI0NhGewg,j26yxl5XnDOPRGxNNaRanQ
975177,The food was amazing. Lots of variety.,2017-06-20,0,K7lWdNUhCbcnEvI0NhGewg,prIuFVl-FExj7SIpoI1qvw
975178,Delicious food and excellent service.,2017-06-23,0,K7lWdNUhCbcnEvI0NhGewg,_81vlR6bA8dqFFDHV3WSyw
975179,Love this place,2017-07-02,0,K7lWdNUhCbcnEvI0NhGewg,2xFC2BGMj_IGClxIPEM4Qg
975180,"Brunch buffet is $48 for all you can eat, and ...",2017-07-02,0,K7lWdNUhCbcnEvI0NhGewg,6AtlFGbu3Ul2aCxCV4eNMQ
975181,Eh...,2017-07-10,0,K7lWdNUhCbcnEvI0NhGewg,1w4wDeUDR_XZnc13Zsg__Q
975182,Food was ok. Pricey... Not much selection Avac...,2017-07-16,0,K7lWdNUhCbcnEvI0NhGewg,BjyM99Jm-iVOg9VIQ7CuRA
975183,Great food!!!! A little bit of everything here...,2017-07-20,0,K7lWdNUhCbcnEvI0NhGewg,j54RE37g56OC-50W9nKn3Q
975184,Go at 2 o'clock! All brunch and lunch selectio...,2017-07-26,0,K7lWdNUhCbcnEvI0NhGewg,FGErqBO-YFVeWhgxFigMMQ
975185,Overpriced. Selection wasn't very good.,2017-07-27,0,K7lWdNUhCbcnEvI0NhGewg,2c5bBbfBLK7ngTbqnKoerQ
975186,Food was great and service even better. Thank ...,2017-08-12,0,K7lWdNUhCbcnEvI0NhGewg,WDTtx4mbULxEzCnjrBUwqA
975187,If you are Marriott Gold or Platinum (or SPG G...,2017-08-17,0,K7lWdNUhCbcnEvI0NhGewg,kt73gkbCTclERl_0zW70iA
975188,Favorite Vegas Buffet!,2017-08-28,0,K7lWdNUhCbcnEvI0NhGewg,R5IcGVGw5geGa4YFzBAF6w
975189,Okay. The presentation is nice but over hyped ...,2017-09-09,0,K7lWdNUhCbcnEvI0NhGewg,fA-4CiZ_Vwq6B-dHdQdfTQ
975190,Best buffets hands down,2017-10-07,0,K7lWdNUhCbcnEvI0NhGewg,k7-SegbJtMYX0Ma2CMPKQQ
975191,The good here was amazing! There wasn't a thin...,2017-10-30,0,K7lWdNUhCbcnEvI0NhGewg,i3NPFGcxD9R7YnTw80DZ5A
975193,Fried chicken is so juicy!!! Worth it.,2017-11-09,0,K7lWdNUhCbcnEvI0NhGewg,yWqZfB6sybmqUtQXJT18CA
975195,Amazingggg!!! So worth the $$$,2017-11-24,0,K7lWdNUhCbcnEvI0NhGewg,yJ23rl893y4uJDRONgXxOg
975196,Not worth for their price.,2017-11-26,0,K7lWdNUhCbcnEvI0NhGewg,2maj3leey-uS4upvLeJs1A

In [231]:
cv = CountVectorizer(binary=False)
cv_fit = cv.fit_transform(xx_cleaned)
# cv.

AttributeError: 'list' object has no attribute 'lower'

In [226]:
import operator
word_list = cv.get_feature_names();    
count_list = cv_fit.toarray().sum(axis=0)
word_count_dic = dict(zip(word_list,count_list))
word_count_dic_sorted = sorted(word_count_dic.items(), key=operator.itemgetter(1))
word_count_dic_sorted.reverse()

NotFittedError: CountVectorizer - Vocabulary wasn't fitted.

In [227]:
word_count_dic_sorted[:5]

[('the', 576), ('and', 326), ('buffet', 280), ('for', 264), ('to', 250)]